hostname: leaf7
interfaces:
  Ethernet1:
    description: MLAG Peer
    trunk: true
  Ethernet2:
    description: Uplink to spine1
    ip: 10.1.15.12/31
  Ethernet3:
    description: Uplink to spine2
    ip: 10.1.15.28/31
  Ethernet4:
    description: Uplink to spine3
    ip: 10.1.15.44/31
  Ethernet5:
    description: Uplink to spine4
    ip: 10.1.15.60/31
  Loopback0:
    description: Router ID
    ip: 10.1.14.11/32
  Vlan10:
    description: User LAN
    ip: 10.1.0.252/26
    vr_ip: 10.1.0.254
  Vlan4094:
    description: MLAG Virtual Interface
    ip: 192.168.0.0/31
loopback_ip: 10.1.14.11/32
mlag_domain: MLAG1
mlag_ip: 192.168.0.0
mlag_peer_ip: 192.168.0.1
vlan10_ip: 10.1.0.252/26
vlan10_virtual_ip: 10.1.0.254
